### ISSUE TITLE
Typo in GetOsLinux.sh

### ISSUE THREAD

**Issue by arvedarved** [Microsoft/pal#56]
s/Softare/Software/

Beware https://github.com/Microsoft/pal/blob/master/test/code/scxsystemlib/common/getlinuxos_test.cpp
tests for this typo too.

**Comment by jeffaco** [comment]
I have a PR out to fix this. The actual problem was in the implementation, and I didn't catch this in the unit tests. Wish I was doing TDD then, this wouldn't have happened.

Mostly cosmetic, but should be fixed. I'll resolve once CI passes and I get signoff.

**Comment by jeffaco** [comment]
Merged, closing issue.
